# Generated by Django 6.0.2 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150)),
                ('card_number', models.CharField(max_length=19)),
                ('exp', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('DC', 'Tarjeta de Débito'), ('PP', 'PayPal'), ('ST', 'Transferencia')], default='DC', max_length=2)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': '3. Payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='ShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('street_address', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('delivery', models.CharField(choices=[('ST', 'Estándar'), ('EX', 'Rápida')], default='EX', max_length=2)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': '2. Shipping',
                'db_table': 'shipping',
            },
        ),
    ]
