# Generated by Django 6.0.2 on 2026-02-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_cuponmodel_options_alter_cuponmodel_code'),
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='Books.bookmodel')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': '2. OrderItems',
                'db_table': 'orderItems',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_shipping', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('street_address', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('delivery', models.CharField(choices=[('ST', 'Estándar'), ('EX', 'Rápida')], default='EX', max_length=2)),
                ('names_payment', models.CharField(max_length=150)),
                ('card_number', models.CharField(max_length=19)),
                ('exp', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('DC', 'Tarjeta de Débito'), ('PP', 'PayPal'), ('ST', 'Transferencia')], default='DC', max_length=2)),
                ('total', models.FloatField()),
                ('cupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': '1. Orders',
                'db_table': 'orders',
            },
        ),
        migrations.DeleteModel(
            name='PaymentModel',
        ),
        migrations.DeleteModel(
            name='ShippingModel',
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Checkout.ordermodel'),
        ),
    ]
