# Generated by Django 6.0.2 on 2026-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_orderitemmodel_ordermodel_delete_paymentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='method',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='names_payment',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_processor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery',
            field=models.CharField(choices=[('ST', 'Estándar'), ('EX', 'Rápida')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
