# Generated by Django 6.0.2 on 2026-03-04 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0003_alter_ordermodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='expected_delivery_from',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='expected_delivery_to',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery',
            field=models.CharField(choices=[('ST', 'Estándar'), ('EX', 'Rápida')], default='ST', max_length=2, verbose_name='Tipo de envio'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='names_shipping',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='street_address',
            field=models.TextField(max_length=255, verbose_name='Dirección de la calle'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
