# Generated by Django 6.0.2 on 2026-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0004_ordermodel_expected_delivery_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
