# Generated by Django 6.0.2 on 2026-03-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0005_ordermodel_delivery_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_method_brand',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_method_last4',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_processor',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_transaction_id',
        ),
    ]
