# Generated by Django 6.0.2 on 2026-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0006_remove_ordermodel_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_shipping', models.CharField(max_length=150, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('street_address', models.TextField(max_length=255, verbose_name='Dirección de la calle')),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('delivery', models.CharField(choices=[('ST', 'Estándar'), ('EX', 'Rápida')], default='ST', max_length=2, verbose_name='Tipo de envio')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'db_table': 'shipping',
            },
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='names_shipping',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
    ]
