# Generated by Django 6.0.2 on 2026-03-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0007_shippingmodel_remove_ordermodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipping', to='Checkout.shippingmodel'),
        ),
    ]
