# Generated by Django 6.0.2 on 2026-03-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0008_ordermodel_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmodel',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
