# Generated by Django 6.0.2 on 2026-03-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0009_alter_shippingmodel_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemmodel',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': '2. Items de pedidos'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Order', 'verbose_name_plural': '1. Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='shippingmodel',
            options={'verbose_name': 'Envio', 'verbose_name_plural': '3. Envios'},
        ),
        migrations.AddField(
            model_name='shippingmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
