# Generated by Django 6.0.2 on 2026-03-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0011_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DELIVERED', 'Entregado'), ('SHIPPED', 'Enviado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
    ]
