# Generated by Django 6.0.2 on 2026-02-08 13:21

import Books.models.author_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('photo_perfil', models.ImageField(upload_to=Books.models.author_model.pathImage)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': '3. Autores',
                'db_table': 'author_book',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': '2. Categorías',
                'db_table': 'category_book',
            },
        ),
    ]
