# Generated by Django 6.0.2 on 2026-02-12 08:15

import Books.models.author_model
import Books.models.book_model
import Books.models.categorie_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('photo_perfil', models.ImageField(upload_to=Books.models.author_model.pathImage)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': '3. Autores',
                'db_table': 'author_book',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=Books.models.categorie_model.pathImage)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': '2. Categorías',
                'db_table': 'category_book',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to=Books.models.book_model.pathImage)),
                ('is_book_of_the_month', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('authors', models.ManyToManyField(related_name='books', to='Books.authormodel')),
                ('categories', models.ManyToManyField(related_name='books', to='Books.categorymodel')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': '1. Libros',
                'db_table': 'books',
            },
        ),
    ]
