# Generated by Django 6.0.2 on 2026-02-08 13:39

import Books.models.book_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=Books.models.book_model.pathImage)),
                ('is_book_of_the_month', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('authors', models.ManyToManyField(related_name='books', to='Books.authormodel')),
                ('categories', models.ManyToManyField(related_name='books', to='Books.categorymodel')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': '1. Libros',
                'db_table': 'books',
            },
        ),
    ]
