# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name='Código de promoción')),
                ('valid_from', models.DateTimeField(verbose_name='Valido desde')),
                ('valid_to', models.DateTimeField(verbose_name='Valido hasta')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta activo?')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
    ]
