# Generated by Django 6.0.2 on 2026-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
