# Generated by Django 6.0.2 on 2026-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_cuponmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuponmodel',
            options={'verbose_name': 'Cupón', 'verbose_name_plural': '4. Cupones'},
        ),
        migrations.AlterField(
            model_name='cuponmodel',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Código de promoción'),
        ),
    ]
