# Generated by Django 6.0.2 on 2026-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_categorymodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
