# Generated by Django 6.0.2 on 2026-02-10 21:15

import Books.models.categorie_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_categorymodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Books.models.categorie_model.pathImage),
        ),
    ]
