# Generated by Django 6.0.2 on 2026-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='Books.bookmodel'),
        ),
    ]
