# Generated by Django 6.0.2 on 2026-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': '1. Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='infousermodel',
            options={'verbose_name': 'Información Personal', 'verbose_name_plural': '2. Informaciones Personales'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='names',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
    ]
