# Generated by Django 6.0.2 on 2026-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousermodel',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
