# Generated by Django 6.0.2 on 2026-03-03 17:34

import Users.models.info_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_infousermodel_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='infousermodel',
            name='photo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=Users.models.info_model.pathImage),
        ),
    ]
